export const FILTER_ACTION = 'filter_action'
export const BEST_SELLING_FILTER_ACTION = 'best_selling_filter_action'
export const LOW_PRICE_FILTER_ACTION = 'low_price_filter_action'
export const HIGH_PRICE_FILTER_ACTION = 'high_price_filter_action'
export const ZERO_PERCENT_PAYMENT_FILTER_ACTION = 'zero_percent_payment_filter_action'
export const ONLINE_OFFER_FILTER_ACTION = 'online_offer_filter_action'